---
- include_vars: ../vars/main.yml

# pre-flight checks ###########################################################

- name: Check that a Remote CIDR was passed into the play as an extra variable
  assert:
    that: 'remote_cidr is defined'

- name: Check that an environment was passed into the play as an extra variable
  assert:
    that: 'aws_env is defined'

- name: Check that keypair name was passed into the play as an extra variable
  assert:
    that: 'key_pair is defined'

- name: Check that keypair name was passed into the play as an extra variable
  assert:
    that: 'key_pair is defined'

- name: Check that database name was passed into the play as an extra variable
  assert:
    that: 'database_name is defined'

- name: Check that database root user name was passed into the play as an extra variable
  assert:
    that: 'database_user is defined'

- name: Check that database root user password was passed into the play as an extra variable
  assert:
    that: 'database_password is defined'

###############################################################################

# 1- create the VPC ###############################################################

- name: Create the VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    state: "present"
  register: myvpc

- name: Create variable for VPC ID
  set_fact:
    vpc_id: "{{ myvpc.vpc.id }}"

# 2- create subnets

- name: Create AZ1 public subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ public_subnet_az1_cidr }}"
    az: "{{ aws_az1 }}"
    state: "present"
    map_public: yes
    tags:
      Name: "{{ aws_env }}_public_az1"
  register: pub_subnet_az1

- name: Create variable for AZ1 public subnet
  set_fact:
    public_subnet_az1_id: "{{ pub_subnet_az1.subnet.id }}"

- name: Create AZ1 private subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ private_subnet_az1_cidr }}"
    az: "{{ aws_az1 }}"
    state: "present"
    region: "{{ aws_region }}"
    tags:
      Name: "{{ aws_env }}_private_az1"
  register: priv_subnet_az1

- name: Create variable for AZ1 private subnet
  set_fact:
    private_subnet_az1_id: "{{ priv_subnet_az1.subnet.id }}"

- name: Create AZ2 public subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ public_subnet_az2_cidr }}"
    az: "{{ aws_az2 }}"
    state: "present"
    region: "{{ aws_region }}"
    map_public: yes
    tags:
      Name: "{{ aws_env }}_public_az2"
  register: pub_subnet_az2

- name: Create variable for AZ2 public subnet
  set_fact:
    public_subnet_az2_id: "{{ pub_subnet_az2.subnet.id }}"

- name: Create AZ2 private subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ private_subnet_az2_cidr }}"
    az: "{{ aws_az2 }}"
    state: "present"
    region: "{{ aws_region }}"
    tags:
      Name: "{{ aws_env }}_private_az2"
  register: priv_subnet_az2

- name: Create variable for AZ2 private subnet
  set_fact:
    private_subnet_az2_id: "{{ priv_subnet_az2.subnet.id }}"

# create Internet gateway for the VPC

- name: Create the Internet gateway for the VPC
  ec2_vpc_igw:
    vpc_id:           "{{ vpc_id }}"
    state:            "present"
    region:           "{{ aws_region }}"
    tags:
      Name:           "{{ aws_env }}_igw"
      VPC:            "{{ vpc_name }}"
      Environment:    "{{ aws_env }}"
  register: myvpc_igw

- name: Create variable for IGW id
  set_fact:
    igw_id: "{{ myvpc_igw.gateway_id }}"

- name: Create AZ1 NAT Gateway
  ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet_az1_id }}"
    wait: yes
    if_exist_do_not_create: true
  register: nat_gateway_az1

- name: Create variable for AZ1 NAT Gateway
  set_fact:
    nat_gateway_id_az1: "{{ nat_gateway_az1.nat_gateway_id }}"

- name: Create AZ2 NAT Gateway
  ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet_az2_id }}"
    wait: yes
    if_exist_do_not_create: true
  register: nat_gateway_az2

- name: Create variable for AZ2 NAT Gateway
  set_fact:
    nat_gateway_id_az2: "{{ nat_gateway_az2.nat_gateway_id }}"

- name: Create public route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: "{{ aws_env }}_public_rt"
    subnets:
      - "{{ public_subnet_az1_id }}"
      - "{{ public_subnet_az2_id }}"
    routes:
      - dest: "{{ public_cidr }}"
        gateway_id: "{{ igw_id }}"
  register: public_route_table

- name: Create AZ1 private route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    tags:
      Name: "{{ aws_env }}_private_rt_az1"
      VPC: "{{ vpc_name }}"
      Environment: "{{ aws_env }}"
    subnets:
      - "{{ private_subnet_az1_id }}"
    routes:
      - dest: "{{ public_cidr }}"
        gateway_id: "{{ nat_gateway_id_az1 }}"

- name: Create AZ2 private route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    tags:
      Name:          "{{ aws_env }}_private_rt_az2"
      VPC:           "{{ vpc_name }}"
      Environment:   "{{ aws_env }}"
    subnets:
      - "{{ private_subnet_az2_id }}"
    routes:
      - dest: "{{ public_cidr }}"
        gateway_id: "{{ nat_gateway_id_az2 }}"

# This is set up so that we can use it in the bastion server rules.
- name: Create private instance security group with no rules.
  ec2_group:
    name: "{{ private_sg_name }}"
    description: "Private instance security group"
    vpc_id: "{{ vpc_id }}"
  register: private_instance_sg

- name: Create variable for private instance security group id
  set_fact:
    private_instance_sg_id: "{{ private_instance_sg.group_id }}"

# Bastion server: can only be accessed by TCP from specified remote IPs
- name: Create security group for bastion server
  ec2_group:
    name: "{{ bastion_sg_name }}"
    description: "Bastion instance security group"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto:      "tcp"
        from_port:  "22"
        to_port:    "22"
        cidr_ip:    "{{ remote_cidr }}"
    rules_egress:
      - proto:      "tcp"
        from_port:  "22"
        to_port:    "22"
        group_name: "{{ private_sg_name }}"
  register: bastion_instance_sg

- name: Create variable for bastion instance security group id
  set_fact:
    private_instance_sg_id: "{{ bastion_instance_sg.group_id }}"

# Private servers: can be accessed http and https from machines in a private subnet
# By SSH must be from Bastion server SG
# This has already been set up so we are just changing it now
- name: Change private instance security group to add rules
  ec2_group:
    name: "{{ private_sg_name }}"
    description: "Private instance security group"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        group_name: "{{ private_sg_name }}"
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        group_name: "{{ bastion_sg_name }}"
      - proto: "tcp"
        from_port: "3306"
        to_port: "3306"
        cidr_ip: "{{ vpc_cidr }}"
    rules_egress:
      - proto: "tcp"
        from_port: "443"
        to_port: "443"
        cidr_ip: "{{ public_cidr }}"
      - proto: "tcp"
        from_port: "22"
        to_port: "22"
        group_name: "{{ private_sg_name }}"
  register: private_instance_sg

- name: Create variable for private instance security group id
  set_fact:
    private_instance_sg_id: "{{ private_instance_sg.group_id }}"

- name: Create public instance security group
  ec2_group:
    name: "{{ public_sg_name }}"
    description: "Public instance security group"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto:      "tcp"
        from_port:  "443"
        to_port:    "443"
        cidr_ip:    "{{ public_cidr }}"
      - proto:      "tcp"
        from_port:  "22"
        to_port:    "22"
        cidr_ip:    "{{ remote_cidr }}"
    rules_egress:
      - proto:      "tcp"
        from_port:  "22"
        to_port:    "22"
        group_name: "{{ private_sg_name }}"
      - proto:      "tcp"
        from_port:  "443"
        to_port:    "443"
        cidr_ip:    "{{ public_cidr }}"
      - proto:      "tcp"
        from_port:  "3306"
        to_port:    "3306"
        group_name: "{{ private_sg_name }}"
  register: public_instance_sg

- name: Create variable for public instance security group id
  set_fact:
    public_instance_sg_id: "{{ public_instance_sg.group_id }}"

- name: Create and associate private network ACL with private subnets
  ec2_vpc_nacl:
    vpc_id: "{{ vpc_id }}"
    name:   "{{ vpc_name}}_private_networkacl"
    subnets: [ "{{ private_subnet_az1_id }}", "{{ private_subnet_az2_id }}" ]
    tags:
      Environment: "{{ aws_env }}"
    ingress: [
        [100, 'tcp', 'allow', "{{ public_cidr }}", null, null, 443, 443],
        [110, 'tcp', 'allow', "{{ vpc_cidr }}", null, null, 22, 22],
        [120, 'tcp', 'allow', "{{ public_cidr }}", null, null, 1024, 65535],
        [130, 'icmp', 'allow', "{{ vpc_cidr }}", -1, -1]
     ]
    egress: [
        [100, 'tcp', 'allow', "{{ public_cidr }}", null, null, 443, 443],
        [110, 'tcp', 'allow', "{{ vpc_cidr }}", null, null, 1024, 65535],
        [120, 'tcp', 'allow', "{{ private_subnet_az1_cidr }}", null, null, 22, 22],
        [130, 'icmp', 'allow', "{{ vpc_cidr }}", -1, -1]
     ]
    state: "present"

- name: Create and associate public network ACL with public subnets
  ec2_vpc_nacl:
    vpc_id: "{{ vpc_id }}"
    name:   "{{ vpc_name}}_public_networkacl"
    subnets: [ "{{ public_subnet_az1_id }}", "{{ public_subnet_az2_id }}" ]
    tags:
      Environment: "{{ aws_env }}"
    ingress: [
        [100, 'tcp', 'allow', "{{ public_cidr }}", null, null, 443, 443],
        [110, 'tcp', 'allow', "{{ remote_cidr }}", null, null, 22, 22],
        [120, 'tcp', 'allow', "{{ public_cidr }}", null, null, 1024, 65535],
        [130, 'icmp', 'allow', "{{ vpc_cidr }}", -1, -1]
     ]
    egress: [
        [100, 'tcp', 'allow', "{{ public_cidr }}", null, null, 443, 443],
        [110, 'tcp', 'allow', "{{ private_subnet_az1_cidr }}", null, null, 3306, 3306],
        [111, 'tcp', 'allow', "{{ private_subnet_az2_cidr }}", null, null, 3306, 3306],
        [120, 'tcp', 'allow', "{{ public_cidr }}", null, null, 1024, 65535],
        [130, 'tcp', 'allow', "{{ private_subnet_az1_cidr }}", null, null, 22, 22],
        [131, 'tcp', 'allow', "{{ private_subnet_az2_cidr }}", null, null, 22, 22],
        [140, 'icmp', 'allow', "{{ public_cidr }}", -1, -1]
     ]
    state: "present"

- name: Create a public machine in AZ1
  ec2_instance:
    name: "{{ aws_env }}-public1"
    key_name: "{{ key_pair }}"
    vpc_subnet_id: "{{ public_subnet_az1_id }}"
    instance_type: t2.micro
    security_group: "{{ public_sg_name }}"
    tenancy: default
    user_data: |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
    instance_role: "{{ iam_role }}"
    network:
      assign_public_ip: true
    image_id: ami-00ee3b59e07408c27
  register: public_ec2_1

- name: Create variable for EC2 ID in public AZ1
  set_fact:
    vpc_id_1: "{{ public_ec2_1.instance_ids[0] }}"

- name: Create a public machine in AZ2
  ec2_instance:
    name: "{{ aws_env }}-public2"
    key_name: "{{ key_pair }}"
    vpc_subnet_id: "{{ public_subnet_az2_id }}"
    instance_type: t2.micro
    security_group: "{{ public_sg_name }}"
    tenancy: default
    user_data: |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
    instance_role: "{{ iam_role }}"
    network:
      assign_public_ip: true
    image_id: ami-00ee3b59e07408c27
  register: public_ec2_2

- name: Create variable for EC2 ID in public AZ2
  set_fact:
    vpc_id_2: "{{ public_ec2_2.instance_ids[0] }}"

- name: Create a private machine in AZ1
  ec2_instance:
    name: "{{ aws_env }}-private1"
    key_name: "{{ key_pair }}"
    vpc_subnet_id: "{{ private_subnet_az1_id }}"
    instance_type: t2.micro
    security_group: "{{ private_sg_name }}"
    tenancy: default
    network:
      assign_public_ip: false
    image_id: ami-00ee3b59e07408c27
  register: private_ec2_1

- name: Create variable for EC2 ID in private AZ1
  set_fact:
    vpc_id_1: "{{ private_ec2_1.instance_ids[0] }}"

- name: Create a bastion machine in AZ1
  ec2_instance:
    name: "{{ aws_env }}-public-bastion"
    key_name: "{{ key_pair }}"
    vpc_subnet_id: "{{ public_subnet_az1_id }}"
    instance_type: t2.micro
    security_group: "{{ bastion_sg_name }}"
    tenancy: default
    network:
      assign_public_ip: false
    image_id: ami-00ee3b59e07408c27
  register: bastion_server


########################
# Set up load balancer
########################

# Make a target group

- name: Create a target group for the two public instances
  elb_target_group:
      name: mytargetgroup
      region: "{{ aws_region }}"
      protocol: http
      port: 80
      vpc_id: "{{ vpc_id }}"
      health_check_path: /
      health_check_port: 80
      health_check_protocol: http
      successful_response_codes: "200,250-260"
      state: present
      wait_timeout: 600
      # wait: True

# Make Application ELB

- name: Create Application Load Balancer for the two public subnets
  elb_application_lb:
    name: myelb
    security_groups:
      - "{{ public_instance_sg_id }}"
    subnets:
      - "{{ public_subnet_az1_id }}"
      - "{{ public_subnet_az2_id }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: mytargetgroup
    state: present

# Add the public EC2 instances to the ELB Target Group
- elb_target:
    target_group_name: mytargetgroup
    target_id: "{{ item }}"
    state: present
  with_items:
    - "{{ vpc_id_1 }}"
    - "{{ vpc_id_2 }}"

#########################
# AURORA DATABASE
#########################

# See if there is a cluster parameter group in this region
- name: check for DB cluster parameter group
  command: >
    aws rds describe-db-cluster-parameter-groups --no-paginate --region eu-west-2
  changed_when: false
  register: db_cluster_parameter_group_query

- name: parse DB cluster parameter group query
  set_fact:
    db_cluster_parameter_group: "{{ db_cluster_parameter_group_query.stdout | from_json | json_query(query)}}"
  vars:
    query: DBClusterParameterGroups[?DBClusterParameterGroupName=='default-cluster-aurora-5-7'] | [0]

# If there isn't one then make a parameter group
- name: create DB cluster parameter group
  command: >
    aws rds create-db-cluster-parameter-group --db-cluster-parameter-group-name default-cluster-aurora-5-7 --db-parameter-group-family aurora-mysql5.7 --description "Default Aurora MySQL 5.7 cluster parameter group created by Ansible" --region eu-west-2
  when: db_cluster_parameter_group == ''

# Make a subnet group, the two private subnets
- name: configure DB subnet group
  rds_subnet_group:
    name: "cluster-subnets"
    description: "Subnets used by Aurora cluster"
    region: eu-west-2
    subnets:
      - "{{ private_subnet_az1_id }}"
      - "{{ private_subnet_az2_id }}"
    state: present

# Check if there is an Aurora cluster in the subnet group
- name: check for Aurora DB cluster
  command: aws rds describe-db-clusters --filters Name=db-cluster-id,Values=cluster-subnets --region eu-west-2
  changed_when: false
  register: aurora_cluster_query

# Parse the response
- name: parse Aurora DB cluster query
  set_fact:
    aurora_cluster: "{{ aurora_cluster_query.stdout | from_json | json_query('DBClusters[0]')}}"
- name: debug
  debug:
    var: aurora_cluster

# Create the database cluster if there is no cluster there already
- name: create Aurora DB cluster
  command: aws rds create-db-cluster --region eu-west-2 --availability-zones "eu-west-2b" "eu-west-2c" --db-cluster-identifier cluster-subnets --engine aurora-mysql --master-username "{{ database_user }}" --master-user-password "{{ database_password }}"
  when: aurora_cluster == ''
  register: aurora_cluster_create
